name: Frontend Pre-Release

on:
  release:
    types: [prereleased]

jobs:
  terraform-plan:
    name: Terraform Plan for pre-release
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::976193222510:role/GithubRole
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/project

      - name: Terraform Plan
        id: tfplan
        run: terraform plan -no-color > tfplan.txt
        working-directory: terraform/project

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-artifact
          path: terraform/project/tfplan.txt

      - name: Send Telegram Notification - Success
        if: ${{ success() }}
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
            -F chat_id="${{ secrets.TG_CHAT_ID }}" \
            -F parse_mode="Markdown" \
            -F text=$'âœ… *Terraform Plan Successful (Frontend Pre-Release)*\n\nğŸ“¦ *Repository:* Hovhannisyan111/frontend\nğŸ·ï¸ *Tag:* ${{ github.event.release.tag_name }}\nğŸ”– *Pre-Release:* ${{ github.event.release.name }}\nğŸ”— [View Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'

      - name: Send Telegram Notification - Failure
        if: ${{ failure() }}
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
            -F chat_id="${{ secrets.TG_CHAT_ID }}" \
            -F parse_mode="Markdown" \
            -F text=$'âŒ *Terraform Plan Failed (Frontend Pre-Release)*\n\nğŸ“¦ *Repository:* Hovhannisyan111/frontend\nğŸ·ï¸ *Tag:* ${{ github.event.release.tag_name }}\nğŸ”– *Pre-Release:* ${{ github.event.release.name }}\nğŸ”— [View Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
